In [1]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)
print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [2]:

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)
print(a.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [3]:

a = np.array([[[1, 2],
               [3, 4]],

              [[5, 6],
               [7, 8]]])

print(a)
print(a.flatten())

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [4]:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Before:", a.shape)

b = a.flatten()

print("After:", b.shape)

Before: (2, 3)
After: (6,)


In [5]:

a = np.array([[10, 20],
              [30, 40],
              [50, 60]])

print(a)
print(a.flatten())

[[10 20]
 [30 40]
 [50 60]]
[10 20 30 40 50 60]


In [6]:

a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(a.reshape(2, 2, 2))   # 3D
print(a.reshape(2, 4))      # 2D

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:


a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a + b)

[ 3  7 11]


In [8]:


a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a - b)

[1 1 1]


In [9]:

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a * b)

[ 2 12 30]


In [10]:


a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a / b)

[2.         1.33333333 1.2       ]


In [11]:

a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(np.dot(a, b))

44


In [12]:


a = np.array([12, 5, 30, 18, 9])

print(np.max(a))

30


In [13]:


a = np.array([12, 5, 30, 18, 9])

print(np.min(a))

5


In [14]:


a = np.array([10, 20, 30, 40, 50])

print(np.sum(a))

150


In [15]:

a = np.array([10, 20, 30, 40, 50])

print(np.mean(a))

30.0


In [16]:

a = np.array([10, 20, 30, 40, 50])

print(np.argmax(a))

4


In [17]:

a = np.array([10, 20, 30, 40, 50])

print(np.argmin(a))

0


In [18]:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.max(a, axis=0))

[40 50 60]


In [19]:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.max(a, axis=1))

[30 60]


In [20]:


a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.min(a, axis=0))

[10 20 30]


In [21]:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.min(a, axis=1))

[10 40]


In [22]:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.sum(a, axis=0))

[50 70 90]


In [23]:

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print(np.sum(a, axis=1))

[ 60 150]


In [28]:
import numpy as np
a = np.array([5, 10, 15, 20, 25, 30])

In [29]:
print(a[0])
print(a[1:5])
print(a[:4])
print(a[::2])
print(a[::-1])

5
[10 15 20 25]
[ 5 10 15 20]
[ 5 15 25]
[30 25 20 15 10  5]
